import { mkdir, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import type { ResolvedConfig, ResolvedProcessConfig } from '../config.js'
import { resolveModules, extractRequires } from './resolver.js'
import { collectTemplates } from './templates.js'
import { emitBundle, emitModule } from './emit.js'
import { renderTemplates } from './vite-render.js'
import { generateRuntimeSource, generateLustacheModules } from './runtime.js'
import { collectAdminTemplates } from './admin.js'
import { ensureAosRepo, copyAosProcessFiles, injectRequire, stripRequires, writeAosYaml } from './aos.js'

export { resolveModules, collectTemplates, emitBundle, emitModule, renderTemplates, generateRuntimeSource, generateLustacheModules }
export { collectAdminTemplates } from './admin.js'
export type { AdminOptions } from './admin.js'
export { parseExternals, resolveExternalUrl } from './vite-render.js'
export { ensureAosRepo, copyAosProcessFiles, injectRequire, stripRequires, generateAosYaml, writeAosYaml } from './aos.js'
export type { AosYamlOptions } from './aos.js'
export type { LuaModule, ResolveResult } from './resolver.js'
export type { TemplateEntry } from './templates.js'
export type { EscapeResult, ParsedExternals } from './vite-render.js'

export interface BundleResult {
  /** Process name from config */
  processName: string
  /** The bundled Lua source */
  output: string
  /** Path the bundle was written to */
  outPath: string
  /** Module names that could not be resolved */
  unresolved: string[]
  /** Number of Lua modules included */
  moduleCount: number
  /** Number of templates inlined */
  templateCount: number
  /** Whether templates were processed through Vite */
  viteProcessed: boolean
  /** Whether the hyperengine runtime module is included */
  runtimeIncluded: boolean
  /** Whether the admin interface module is included */
  adminIncluded: boolean
  /** Artifact type: 'process' or 'module' */
  type: 'process' | 'module'
  /** Whether this was built as an aos module */
  aosModule: boolean
  /** Files copied from the aos repo (when aosModule is true) */
  aosCopiedFiles: string[]
  /** Path to the generated YAML config file (when aosModule is true) */
  aosYamlPath: string | null
  /** Module names whose require() calls were stripped from process.lua */
  aosExcludedModules: string[]
  /** Dependencies marked as external for Vite template processing */
  viteExternals: (string | RegExp)[]
}

interface AosOpts {
  enabled: boolean
  commit: string
  stack_size: number
  initial_memory: number
  maximum_memory: number
  target: 32 | 64
  compute_limit: string
  module_format: string
  exclude: string[]
}

/**
 * Run the full bundling pipeline for a single process: resolve → collect templates → emit.
 */
export async function bundleProcess(
  process: ResolvedProcessConfig,
  aos: AosOpts = { enabled: false, commit: '', stack_size: 3_145_728, initial_memory: 4_194_304, maximum_memory: 1_073_741_824, target: 32, compute_limit: '9000000000000', module_format: 'wasm32-unknown-emscripten-metering', exclude: [] },
): Promise<BundleResult> {
  const adminEnabled = process.adminInterface.enabled

  // 1. Generate runtime module first so we can discover its dependencies
  const runtimeSource = await generateRuntimeSource({ handlers: process.handlers, patchKey: process.patchKey, stateKey: process.stateKey })

  // 1b. Generate lustache modules (bundled directly, no luarocks needed)
  const lustacheModules = await generateLustacheModules()

  // 2. Resolve Lua modules (include admin + runtime dependencies)
  const autoGenerated = new Set(['templates', 'hyperengine', 'hyperengine-admin', 'lustache', 'lustache.context', 'lustache.renderer', 'lustache.scanner'])
  const runtimeDeps = extractRequires(runtimeSource).filter(d => !autoGenerated.has(d))
  const extraDeps = [...(adminEnabled ? ['admin'] : []), ...runtimeDeps]
  const { modules, unresolved } = await resolveModules(process, extraDeps)

  // Inject configured adminInterface.path into admin module
  if (adminEnabled) {
    const adminMod = modules.find(m => m.name === 'admin')
    if (adminMod) {
      adminMod.source = adminMod.source.replace(
        /local _path = ['"]admin['"]/,
        `local _path = "${process.adminInterface.path}"`,
      )
    }
  }

  // 2. Collect templates
  const { entries, luaSource: templatesLua } = await collectTemplates(process)

  // 2b. Collect admin templates and merge
  let allEntries = entries
  if (adminEnabled) {
    const adminEntries = await collectAdminTemplates({
      dir: process.adminInterface.dir,
    })
    allEntries = [...entries, ...adminEntries]
  }

  // 3. Process templates through Vite if enabled
  const viteEnabled = !!process.templates.vite
  let templatesSource: string | null = null

  if (allEntries.length > 0) {
    if (viteEnabled) {
      const additionalDirs = adminEnabled
        ? [{ prefix: 'admin', dir: process.adminInterface.dir }]
        : []
      const processed = await renderTemplates(allEntries, process, additionalDirs)
      // Re-generate Lua source from Vite-processed entries
      const { toLuaLongString } = await import('./templates.js')
      const lines: string[] = ['local _templates = {}']
      for (const entry of processed) {
        lines.push(`_templates["${entry.key}"] = ${toLuaLongString(entry.content)}`)
      }
      lines.push('return _templates')
      templatesSource = lines.join('\n')
    } else {
      // Generate Lua source from all entries (including admin)
      const { toLuaLongString } = await import('./templates.js')
      const lines: string[] = ['local _templates = {}']
      for (const entry of allEntries) {
        lines.push(`_templates["${entry.key}"] = ${toLuaLongString(entry.content)}`)
      }
      lines.push('return _templates')
      templatesSource = lines.join('\n')
    }
  }

  // 4. Emit bundle
  // Admin is now a regular module resolved from src/admin/init.lua
  const autoRequireModules = adminEnabled ? ['admin'] : undefined
  const isModule = process.type === 'module'
  const useAos = aos.enabled && !isModule
  const output = useAos
    ? emitModule(modules, templatesSource, runtimeSource, process.handlers, autoRequireModules, lustacheModules)
    : emitBundle(modules, templatesSource, runtimeSource, process.handlers, autoRequireModules, lustacheModules)

  // 6. Determine output paths
  // When aos is enabled (for processes only), nest under processName subdir
  const processOutDir = useAos ? resolve(process.outDir, process.name) : process.outDir
  const outFile = useAos ? `${process.name}.lua` : process.outFile
  const outPath = resolve(processOutDir, outFile)
  await mkdir(dirname(outPath), { recursive: true })
  await writeFile(outPath, output, 'utf-8')

  // 7. Handle aos module output: clone repo, copy files, inject require, write YAML (processes only)
  let aosCopiedFiles: string[] = []
  let aosYamlPath: string | null = null
  let aosExcludedModules: string[] = []
  if (useAos) {
    const repoPath = await ensureAosRepo(aos.commit, process.root)
    aosCopiedFiles = await copyAosProcessFiles(repoPath, processOutDir)
    const aosProcessLua = resolve(processOutDir, 'process.lua')
    await injectRequire(aosProcessLua, process.name)
    aosExcludedModules = await stripRequires(aosProcessLua, aos.exclude)
    aosYamlPath = await writeAosYaml(processOutDir, {
      stack_size: aos.stack_size,
      initial_memory: aos.initial_memory,
      maximum_memory: aos.maximum_memory,
      target: aos.target,
      aos_git_hash: aos.commit,
      compute_limit: aos.compute_limit,
      module_format: aos.module_format,
    })
  }

  const viteExternals: (string | RegExp)[] = viteEnabled && process.templates.vite
    ? ((process.templates.vite as Exclude<typeof process.templates.vite, false>).external ?? []).map(
        (e) => (typeof e === 'object' && !(e instanceof RegExp) && 'name' in e) ? e.name : e,
      )
    : []

  return {
    processName: process.name,
    type: process.type,
    output,
    outPath,
    unresolved,
    moduleCount: modules.length,
    templateCount: allEntries.length,
    viteProcessed: viteEnabled && allEntries.length > 0,
    runtimeIncluded: true,
    adminIncluded: adminEnabled,
    aosModule: useAos,
    aosCopiedFiles,
    aosYamlPath,
    aosExcludedModules,
    viteExternals,
  }
}

/**
 * Run the full bundling pipeline for all processes in parallel.
 */
export async function bundle(config: ResolvedConfig): Promise<BundleResult[]> {
  return Promise.all(config.processes.map(p => bundleProcess(p, config.aos)))
}
